---
title: "HoffmanS_FirstDraft"
output: html_document
date: "2024-11-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, error = FALSE, warning = FALSE)
```

## Project Set-up

```{r set-up}
#Load Packages
library(tidyr)
library(leaflet)
library(ggplot2)
library(dplyr)
library(sf)
library(readxl)
library(sp)
library(htmltools)
library(RColorBrewer)
library(tidygeocoder)
library(tidycensus)
library(tigris)
library(units)
library(ggfortify)
library(broom)
library(lubridate)
library(car)

#Set Working Directory
setwd("/Users/sarahhoffman/Library/CloudStorage/OneDrive-UniversityofMaryland/data_sources")
```

## School Location


```{r school 1}
#Create Data Table of School Locations and limit columns
public.schools <- read.csv("school_locations.csv") %>%
                  select(NAME, LATITUDE, LONGITUDE)
```

``` {r geocoding charter, eval = FALSE}
#Create Data Table of Charter Schools
charter.schools <- read.csv("charter_schools.csv") %>%
                  geocode(Address, method = 'osm', lat = latitude, long = longitude) %>% #Convert addresses to coordinates
                  select(charter.latlong, School.Name, latitude, longitude) %>% 
#Limit columns
colnames(charter.schools) <- c("NAME", "LATITUDE", "LONGITUDE") #Change column names

#Manually input NA data
charter.schools[59, 2] <- 38.85632429624879
charter.schools[59, 3] <- -76.98913290464318
charter.schools[69, 2] <- 38.83197915527436
charter.schools[69, 3] <- -77.01854284512433

#Combine public and charter schools
school.locations <- rbind(public.locations, charter.locations)

#Download as csv file for future use
write.csv(school.locations, "/Users/sarahhoffman/Library/CloudStorage/OneDrive-UniversityofMaryland/data_sources/schoolcoordinates.csv", row.names = TRUE)
```

```{r school 2}
#Load school locations
school.locations <- read.csv("schoolcoordinates.csv")

#Create school radius
school.radius <- school.locations %>%
                st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326) %>%
                sf::st_buffer (dist = 402)

head(school.radius)
```

## Crash Data
```{r crash}
#Create Data Table of Crashes Involving Pedestrians
crash <- read_xlsx(path = "crashes_19_23.xlsx", sheet = "crashes_19_23_ped") %>%
   #Convert crash coordinates to sf           
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326) 

#Match crashes to school
crash_filter <- st_filter(crash, school.radius) %>% #Filter to those that fall within radius
                      st_join(left = TRUE, school.radius["NAME"]) 
  
#Transform report date column to as.POSIXct
crash_filter$REPORTDATE <- as.POSIXct(crash_filter$REPORTDATE, format = "%Y/%m/%d %H:%M:%S")
  
#Create columns for year, month, day of week, and hours of day
crash_filter <- crash_filter %>%
                mutate(year = year(crash_filter$REPORTDATE), 
                       month = month(crash_filter$REPORTDATE, label = TRUE), 
                       day = wday(REPORTDATE, label = TRUE), 
                       hour =  hour(REPORTDATE))

head(crash_filter)

#Count number of crashes, number of pedestrians, and number of major and fatal injuries
crash_school <- crash_filter %>%                      
  group_by(NAME) %>%
  summarise(total_crashes = n(), 
            total_pedestrians = sum(TOTAL_PEDESTRIANS), 
            maj_fat = sum(MAJORINJURIES_PEDESTRIAN, FATAL_PEDESTRIAN))

#Join crash_school data with school location
school.crash <- school.locations %>% 
  full_join(crash_school, by = c("NAME"), suffix=c("",".y")) %>%
  full_join(school.radius, by = c("NAME"), suffix=c("",".y"))

#Change NA to 0
school.crash <- school.crash %>%
  mutate_at(vars(total_crashes, total_pedestrians, maj_fat), ~replace_na(., 0))

head(school.crash)
```

## Crash Graphs
```{r crash graphs 1}
#Look at crashes by year
crashes_year <- crash_filter %>%
  group_by(year) %>%
  summarize(total_crashes = n(), .groups = 'drop') 

crashes_year_label <- format(round(crashes_year$total_crashes, digits = 0),big.mark=",")

ggplot(crashes_year, aes(year, total_crashes)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Number of Pedestrian Involved Crashes by Year", 
       x = "Year", 
       y = "Number of Crashes") +
  geom_text(aes(label=crashes_year_label),  position=position_dodge(width=0.9), vjust=-0.25) 

#Look at top schools
crashes_school <- crash_filter %>%
  group_by(NAME) %>%
  summarize(total_crashes = n(), .groups = 'drop') %>%
  arrange(desc(total_crashes)) %>%
  slice_head(n = 10)

crashes_school <- crashes_school %>%
                  st_drop_geometry(.)

crashes_school_radius <- school.radius %>%
                        right_join(crashes_school, by = "NAME")

crashes_school_label <- format(round(crashes_school$total_crashes, digits = 0),big.mark=",")

ggplot(crashes_school, aes(total_crashes, reorder(NAME, total_crashes))) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Top 10 Schools for \nPedestrian Involved Crashes", 
       x = "Total Crashes", 
       y = "School") +
  scale_x_continuous(limits = c(0,130)) +
  geom_text(aes(label=crashes_school_label),  position=position_dodge(width=0.9), hjust=-0.25, size = 3) 
```

```{r top schools, results = 'hide'}

dc.outline <- counties(state = "DC", year = 2022)
dc.roads <- roads(state = "DC", county = "District of Columbia", year = 2022)
```

```{r crash graphs 2}
ggplot() +
  geom_sf(data = dc.outline, color = "grey", fill = "white") +
  geom_sf(data = dc.roads, color = "grey") +
  geom_sf(data = crashes_school_radius, size = 5, color = "blue", alpha = 0.5) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line.y = element_blank(),
    axis.text.y = element_blank(), 
    axis.line.x = element_blank(),
    axis.text.x = element_blank(),
  ) +
  labs(title = "Top 10 Schools for Pedestrian Involved Crashes") 

ggplot() +
  geom_sf(data = dc.roads, color = "grey", fill = "white") +
  geom_sf(data = crashes_school_radius, size = 5, color = "blue", alpha = 0.5) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line.y = element_blank(),
    axis.text.y = element_blank(), 
    axis.line.x = element_blank(),
    axis.text.x = element_blank(),
  ) +
  scale_x_continuous(limits = c(-77.05,-77.00)) +
  scale_y_continuous(limits = c(38.87,38.95)) +
  labs(title = "Top 10 Schools for \nPedestrian Involved Crashes") 

#Look at top schools for crashes by year
crashes_year_school <- crash_filter %>%
  group_by(year, NAME) %>%
  summarize(total_crashes = n(), .groups = 'drop') %>%
  arrange(year, desc(total_crashes)) %>%
  group_by(year) %>%
  slice_head(n = 5)  %>% 
  mutate (ToHighlight = ifelse(total_crashes == max(total_crashes), "yes", "no"))

school_data <- format(round(crashes_year_school$total_crashes, digits = 0),big.mark=",")

ggplot(crashes_year_school, aes(y = NAME, x = total_crashes, fill = ToHighlight)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ year, scales = "fixed", nrow = 1) +  # Create a separate plot for each year
  geom_text(aes(label=school_data),  position=position_dodge(width=1), vjust=-1, hjust=-0.25, size = 3) + #Add data labels
  labs(title = "Top 5 Schools for \nNumber of Pedestrian-Involved \nCrashes by Year", 
       x = "Total Crashes", 
       y = "School") +
  scale_x_continuous(limits = c(0,50), breaks = seq(0, 50, by = 5)) +
  theme(axis.text.y = element_text( hjust = 1), 
        axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(), 
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())  

#Look at crashes by month
crashes_month <- crash_filter %>%
  group_by(month) %>%
  summarize(total_crashes = n(), .groups = 'drop') 

crashes_month_label <- format(round(crashes_month$total_crashes, digits = 0),big.mark=",")

ggplot(crashes_month, aes(month, total_crashes)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Number of Pedestrian Involved Crashes by Month", 
       x = "Month", 
       y = "Number of Crashes") +
  geom_text(aes(label=crashes_month_label),  position=position_dodge(width=0.9), vjust=-0.25) 

#Look at crashes by day of week
crashes_day <- crash_filter %>%
  group_by(day) %>%
  summarize(total_crashes = n(), .groups = 'drop') 

crashes_day_label <- format(round(crashes_day$total_crashes, digits = 0),big.mark=",")

ggplot(crashes_day, aes(day, total_crashes)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Number of Pedestrian Involved Crashes by Day of Week", 
       x = "Day of Week", 
       y = "Number of Crashes") +
  geom_text(aes(label=crashes_day_label),  position=position_dodge(width=0.9), vjust=-0.25) 


#Look at crashes by hour of day
crashes_hour <- crash_filter %>%
  group_by(hour) %>%
  summarise(total_crashes = n()) %>%
  arrange(hour)

hour_labels <- c("12", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11")
crashes_hour_label <- format(round(crashes_hour$total_crashes, digits = 0),big.mark=",")

ggplot(crashes_hour, aes(x = factor(hour), y = total_crashes)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Number of Pedestrian Involved Crashes by Hour of the Day",
       x = "Hour of Day",
       y = "Number of Crashes") +
  geom_text(aes(label=crashes_hour_label),  position=position_dodge(width=0.9), vjust=-0.25, size = 3) +
  theme_minimal() +
  scale_x_continuous(breaks = 0:23) + # Set x-axis to show all hours
  scale_x_discrete(labels = hour_labels) +
  theme(
    axis.line.y = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```

## Tree Location Data
```{r tree location}
#Load tree location data
tree <- read.csv("number_trees.csv") %>%
        filter(!is.na(X)) %>%
        filter(!is.na(Y)) %>%
        sf::st_as_sf(coords = c("X", "Y"), crs = 26985) %>% #Convert x and y coordinates to longitude and latitude
        st_transform(crs = 4326) %>%
        mutate(lat= st_coordinates(.)[,1],
        lon = st_coordinates(.)[,2]) %>%
        st_as_sf(coords = c("longitude", "latitude"), crs = 4326) #Convert back to sf

#Switch longitude and latitude columns
colnames(tree)[54] <- paste("longitude")
colnames(tree)[55] <- paste("latitue")

#Filter those trees that fall within schools 
tree.school <- tree %>%
              st_filter(school.radius) %>%
              st_join(left = TRUE, school.radius["NAME"]) %>%
              group_by(NAME) %>%
              summarise(total_trees = n(), avg_crown = mean(CROWN_AREA, na.rm = TRUE)) #Count number of trees and average crown area

#Combine school location data with tree data
school.crash.tree <- school.crash %>% 
  full_join(tree.school, by = "NAME", suffix=c("",".y")) %>%
  select(-ends_with(".y")) %>%
  mutate(avg_crown = round(avg_crown, 0))

#Look at top ten schools for tree density
treed_school <- school.crash.tree %>%
  arrange(desc(total_trees)) %>%
  slice_head(n = 10)

treed_school_label <- format(round(treed_school$total_trees, digits = 0),big.mark=",")

ggplot(treed_school, aes(total_trees, reorder(NAME, total_trees))) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Top 10 Schools for \nTree Density", 
       x = "Total Trees", 
       y = "School") +
  scale_x_continuous(limits = c(0,2000)) +
  geom_text(aes(label=treed_school_label),  position=position_dodge(width=0.9), hjust=-0.25, size = 3)

treed_school <- treed_school %>%
                  st_drop_geometry(.)

treed_school_radius <- school.radius %>%
                        right_join(treed_school, by = "NAME")
ggplot() +
  geom_sf(data = dc.outline, color = "grey", fill = "white") +
  geom_sf(data = dc.roads, color = "grey") +
  geom_sf(data = treed_school_radius, size = 5, color = "blue", alpha = 0.5) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line.y = element_blank(),
    axis.text.y = element_blank(), 
    axis.line.x = element_blank(),
    axis.text.x = element_blank(),
  ) +
  labs(title = "Top 10 Schools for Tree Density")
```

## Tree Coverage Data
```{r tree coverage}
#Create data table of tree coverage data
tree.coverage <- read.csv("treecanopy_20_all.csv") %>%
  select(GEOID, UTC_PCT) %>%
  transform(GEOID = as.character(GEOID))

#Update block groups to match 2022
crosswalk <- read.csv("crosswalk.csv") %>%
              select(bg2010ge, bg2020ge) %>%
              transform(bg2010ge = as.character(bg2010ge), 
                        bg2020ge = as.character(bg2020ge))
```

```{r block group, results = 'hide'}
#Get block group geometries
dc.blocks <- block_groups(state = "DC", year = 2010)
```

```{r join block groups}
#Join block group geometries with tree coverage data
tree.coverage.geometry <- tree.coverage %>%
  full_join(dc.blocks, by = c("GEOID" = "GEOID10")) %>%
  left_join(crosswalk, by = c("GEOID" = "bg2010ge")) %>%
  st_as_sf(., crs = 4326)

#Match tree coverage tracts to schools
tree.coverage.match <- st_join(school.radius, tree.coverage.geometry, largest = TRUE)

#Combine tree coverage with crash and tree count data
school.cr.tr.co <- school.crash.tree %>%
  full_join(tree.coverage.match, by = "NAME", suffix=c("",".y")) %>%
  select(-ends_with(".y")) 
school.cr.tr.co$bg2020ge <- as.character(school.cr.tr.co$bg2020ge)

#Look at top 10 schools for tree coverage
treec_school <- school.cr.tr.co %>%
  arrange(desc(UTC_PCT)) %>%
  slice_head(n = 10)

ggplot(treec_school, aes(UTC_PCT, reorder(NAME, UTC_PCT))) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Top 10 Schools for \nTree Coverage", 
       x = "Percent Urban Tree Coverage", 
       y = "School") +
  scale_x_continuous(limits = c(0,100)) +
  geom_text(aes(label=UTC_PCT),  position=position_dodge(width=0.9), hjust=-0.25, size = 3)

treec_school <- treec_school %>%
                  st_drop_geometry(.)

treec_school_radius <- school.radius %>%
                        right_join(treec_school, by = "NAME")
ggplot() +
  geom_sf(data = dc.outline, color = "grey", fill = "white") +
  geom_sf(data = dc.roads, color = "grey") +
  geom_sf(data = treec_school_radius, size = 5, color = "blue", alpha = 0.5) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line.y = element_blank(),
    axis.text.y = element_blank(), 
    axis.line.x = element_blank(),
    axis.text.x = element_blank(),
  ) +
  labs(title = "Top 10 Schools for Tree Coverage")
```

## Median Income and Population Data
```{r income and population}
#Set Census Api Key
census_api_key("9ac1cc1ce7936fa370a67b3f87d37169566116f6")
```
``` {r block data, results = 'hide'}
#Get population and median income data for block groups
block.data <- get_acs(geography = "block group",
                     state = "DC",
                     year = 2022,
                     survey = "acs5", 
                     output = "wide",
                     variables = c(medincome = "B19013_001", pop = "B01003_001"),
                     geometry = TRUE) %>%
                    mutate(area = st_area(.))
```

```{r census}
#Check missing values
colSums(is.na(block.data))

#Isolate rows with missing med income
block.data.inc.na <- block.data[is.na(block.data$medincomeE),]

#Load variables on household count by income category
inc.variables <- c("10" = "B19001_002", "10.15" = "B19001_003", 
                   "15.20" = "B19001_004", "20.25" = "B19001_005", "25.30" = "B19001_006", 
                   "30.35" = "B19001_007", "35.40" = "B19001_008", "40.45" = "B19001_009", 
                   "45.50" = "B19001_010", "50.60" = "B19001_011", "60.75" = "B19001_012", 
                   "75.100" = "B19001_013", "100.125" = "B19001_014", "125.150" = "B19001_015", 
                   "150.200" = "B19001_016", "200" = "B19001_017")

block.inc <- get_acs(geography = "block group",
                      state = "DC",
                      year = 2022,
                      survey = "acs5", 
                      output = "tidy",
                      variables = inc.variables) 

block.inc$GEOID <- as.numeric(block.inc$GEOID)
block.inc$variable <- as.numeric(block.inc$variable)

#Find 50th percentile income category
inc.imp <- block.inc %>%
          group_by(GEOID) %>%
          summarise(med = median(rep(variable,estimate), na.rm = TRUE))

inc.imp$GEOID <- as.character(inc.imp$GEOID)

#Impute estimate of median income based on range
inc.imp <- inc.imp %>%
          mutate(medincomeE = ifelse(med == "10", 10000, ifelse(med == "10.15", 12500, ifelse(med == "15.20", 17500, ifelse(med == "20.25", 22500, ifelse(med == "25.30", 27500, ifelse(med == "30.35", 32500, ifelse(med == "35.40", 37500, ifelse(med == "40.45", 42500, ifelse(med == "45.50", 47500, ifelse(med == "50.60", 55000, ifelse(med == "60.75", 67500, ifelse(med == "75.100", 87500, ifelse(med == "100.125", 125000, ifelse(med == "125.150", 137500, ifelse(med == "150.200", 175000, 200000))))))))))))))))

#Apply imputed values to original dataset
block.data.inc.imp <- block.data.inc.na %>%
                      left_join(inc.imp, by = "GEOID", suffix=c(".x","")) %>%
                      select(GEOID, medincomeE) %>%
                      st_drop_geometry(.)

block.data <- block.data %>%
              left_join(block.data.inc.imp, by = "GEOID") 

block.data$medincomeE.y <- ifelse(is.na(block.data$medincomeE.y), block.data$medincomeE.x, block.data$medincomeE.y)              

block.data <- block.data %>%
              select(-medincomeE.x)

#Check missing values again
colSums(is.na(block.data))

#Calculate population density and proportion of population

block.data$area <- set_units(block.data$area, km^2)
block.data <- block.data %>%
              mutate(density = (popE/area)/1000) %>%
              mutate(pop_prop = popE/sum(popE))

#Join population and median income with combined data 
school.cr.tr.co.ce <- school.cr.tr.co %>%
  left_join(block.data, by = c("bg2020ge" = "GEOID"))
```

## Road Classification, Speed limit, and Traffic Volume Data
```{r road, speed, and traffic 1}
#Load road classification data
road <- read.csv("roadway_classification.csv") %>%
              select(SPEEDLIMITS_OB, DCFUNCTIONALCLASS, ADDRESS)
```

``` {r geocoding roads, eval=FALSE}
#Geocode road coordinates
road <- road %>%
        geocode(ADDRESS, method = "osm", lat = latitude, lon = longitude)

#Save csv file for later use
st_write(road, "/Users/sarahhoffman/Library/CloudStorage/OneDrive-UniversityofMaryland/data_sources/roadcoordinates.csv")
```

```{r road, speed, and traffic 2}
#Load in csv file
road <- read.csv("roadcoordinates.csv")

#Omit NA values and convert to sf
road.clean <- na.omit(road) %>%
            st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

#Change 0 values for AADT to NA
road.clean$AADT[road.clean$AADT == 0] <- NA

#Create column to count major arterial and minor arterial roads
road.clean <- road.clean %>%
              mutate(arterial = ifelse(DCFUNCTIONALCLASS == 14, TRUE, ifelse(DCFUNCTIONALCLASS ==16, TRUE, FALSE)))

#Filter and join roads to school radius
road.school <- st_filter(road.clean, school.radius) %>% #Filter to those that fall within radius
  st_join(left = TRUE, school.radius["NAME"]) %>% #Match crashes to a school
  group_by(NAME) %>%
  summarise(avg_speed = mean(SPEEDLIMITS_OB), n_roads = n(), n_arterial = sum(arterial), prop_arterial = n_arterial/n_roads, total_vol = sum(AADT, na.rm = TRUE)) #Calculate average speed limit, number and proportion of arterial roads, and sum of AADT
road.school$total_vol[road.school$total_vol == 0] <- NA

#Join with school data set
school.cr.tr.co.ce.rd <- school.cr.tr.co.ce %>% 
  full_join(road.school, by = c("NAME.x" = "NAME"), suffix=c("",".y")) 

#Select columns
school.data <- school.cr.tr.co.ce.rd %>%
              select(c(NAME.x, total_crashes, total_pedestrians, maj_fat, total_trees, avg_crown, UTC_PCT, GEOID, bg2020ge, medincomeE.y, medincomeM, popE, popM, geometry.y, density, pop_prop, avg_speed, n_roads, n_arterial, prop_arterial, total_vol))

#Create column that calculates proportion of pedestrians involved that had major or fatal injuries
school.data <- school.data %>%
              mutate(prop_majfat = maj_fat/total_pedestrians) 

#Change NA Values to O
school.data$prop_majfat[is.na(school.data$prop_majfat)] <- 0
```

## Safe Routes to School Data
```{r SRTS}
#Load in SRTS data 
school.srts <- read.csv("SRTS.csv")

#Join SRTS data with school.data
school.data <- school.data %>%
  left_join(school.srts, by = "NAME.x")
```

## Log transformation
```{r log}
#Add log transformations for total crashes, median income, and proportion of major/fatal injuries
school.data <- school.data %>%
              mutate(log_crash = log(total_crashes),
                     log.income = log(medincomeE.y),
                     log_majfat = log(prop_majfat))

#Change -Inf values to 0
school.data$log_crash[school.data$log_crash == -Inf] <- 0

#Change -Inf values to -4
school.data$log_majfat[!is.finite(school.data$log_majfat)] <- -4
```


## Summary Statistics
```{r summary statistics}
#Total Crashes
summary(school.data$total_crashes)
boxplot(school.data$total_crashes)

#Total Pedestrians Involved
summary(school.data$total_pedestrians)
boxplot(school.data$total_pedestrians)

#Number of major or fatal injuries
summary(school.data$maj_fat)
boxplot(school.data$maj_fat)

#Proportion of major or fatal injuries
summary(school.data$prop_majfat)
boxplot(school.data$prop_majfat)

#Total Trees
summary(school.data$total_trees)
boxplot(school.data$total_trees)

#Average crown area
summary(school.data$avg_crown)
boxplot(school.data$avg_crown)

#Percent Urban Tree Coverage
summary(school.data$UTC_PCT)
boxplot(school.data$UTC_PCT)

#Median Income
summary(school.data$medincomeE.y)
boxplot(school.data$medincomeE.y)

#Population
summary(school.data$popE)
boxplot(school.data$popE)

#Average Speed Limit
summary(school.data$avg_speed)
boxplot(school.data$avg_speed)

#Number of Roads
summary(school.data$n_roads)
boxplot(school.data$n_roads)

#Proportion Arterial
summary(school.data$prop_arterial)
boxplot(school.data$prop_arterial)

#Traffic Volume
summary(school.data$total_vol)
boxplot(school.data$total_vol)

#Density
summary(school.data$density)
boxplot(school.data$density)

#Standard Deviation
school.data.sd <- school.data %>%
  select(total_crashes, total_pedestrians, maj_fat, prop_majfat, total_trees,
         avg_crown, UTC_PCT, medincomeE.y, popE,
         avg_speed, n_roads, prop_arterial, total_vol) %>%
  apply(2, sd, na.rm = TRUE)

school.data.sd
```

## Histogram charts
``` {r histogram}
#Histogram of number of pedestrian involved crashes
ggplot(school.data, aes(x = total_crashes)) +
  geom_histogram(binwidth = 5, color = "darkgrey", fill = "grey") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  scale_x_continuous(breaks = seq(0,120,10)) +
  labs(title = "Distribution of Pedestrian \nInvolved Crashes in School Radius", 
       x = "Total Number of Pedestrian Involved Crashes", 
       y = "Count") +
  geom_vline(aes(xintercept = mean(total_crashes)), color = "blue", alpha = 0.7) +
  geom_vline(aes(xintercept = median(total_crashes)), color = "darkorange", alpha = 0.7) +
  geom_text(aes(x=mean(total_crashes), label="\nMean", y=40), colour="blue", angle=90) +
  geom_text(aes(x=median(total_crashes), label="Median\n", y=40), colour="darkorange", angle=90)

#Histogram of log of pedestrian involved crashes
ggplot(school.data, aes(x = log_crash)) +
  geom_histogram(binwidth = 0.5, color = "darkgrey", fill = "grey") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Distribution of Pedestrian \nInvolved Crashes in School Radius (log)", 
       x = "Total Number of Pedestrian Involved Crashes (log)", 
       y = "Count") +
  scale_x_continuous(breaks = seq(0,5,0.5)) +
  geom_vline(aes(xintercept = mean(log_crash)), color = "blue", alpha = 0.7) +
  geom_vline(aes(xintercept = median(log_crash)), color = "darkorange", alpha = 0.7) +
  geom_text(aes(x=mean(log_crash), label="Mean\n", y=10), color="blue", angle=90) +
  geom_text(aes(x=median(log_crash), label="\nMedian", y=10), color="darkorange", angle=90)

#Histogram of proportion of major or fatal injuries
ggplot(school.data, aes(x = prop_majfat)) +
  geom_histogram(binwidth = 0.1, color = "darkgrey", fill = "grey") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Distribution of the Proportion \nof Major or Fatal Injuries", 
       x = "Proportion of Major or Fatal Injuries", 
       y = "Count") +
  scale_x_continuous(breaks = seq(0,1,0.1)) +
  geom_vline(aes(xintercept = mean(prop_majfat)), color = "blue", alpha = 0.7) +
  geom_vline(aes(xintercept = median(prop_majfat)), color = "darkorange", alpha = 0.7) +
  geom_text(aes(x=mean(prop_majfat), label="\nMean", y=50), color="blue", angle=90) +
  geom_text(aes(x=median(prop_majfat), label="Median\n", y=50), color="darkorange", angle=90)

#Histogram of proportion of major or fatal injuries (log)
ggplot(school.data, aes(x = log_majfat)) +
  geom_histogram(binwidth = 0.5, color = "darkgrey", fill = "grey") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Distribution of the Proportion \nof Major or Fatal Injuries (log)", 
       x = "Proportion of Major or Fatal Injuries (log)", 
       y = "Count") +
  scale_x_continuous(breaks = seq(-4,0,0.5)) +
  geom_vline(aes(xintercept = mean(log_majfat)), color = "blue", alpha = 0.7) +
  geom_vline(aes(xintercept = median(log_majfat)), color = "darkorange", alpha = 0.7) +
  geom_text(aes(x=mean(log_majfat), label="Mean\n", y=50), color="blue", angle=90) +
  geom_text(aes(x=median(log_majfat), label="\nMedian", y=50), color="darkorange", angle=90)

#Histogram of tree density
ggplot(school.data, aes(x = total_trees)) +
  geom_histogram(binwidth = 50, color = "darkgrey", fill = "grey") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  scale_x_continuous(breaks = seq(0,2000,250)) +
  labs(title = "Distribution of Tree Density", 
       x = "Number of Trees", 
       y = "Count") +
  geom_vline(aes(xintercept = mean(total_trees)), color = "blue", alpha = 0.7) +
  geom_vline(aes(xintercept = median(total_trees)), color = "darkorange", alpha = 0.7) +
  geom_text(aes(x=mean(total_trees), label="Mean\n", y=5), color="blue", angle=90) +
  geom_text(aes(x=median(total_trees), label="\nMedian", y=5), color="darkorange", angle=90)

#Histogram of tree coverage
ggplot(school.data, aes(x = UTC_PCT)) +
  geom_histogram(binwidth = 5, color = "darkgrey", fill = "grey") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  scale_x_continuous(breaks = seq(0,80,10)) +
  scale_y_continuous(breaks = seq(0,60,10)) +
  labs(title = "Distribution of Percent Urban Tree Coverage", 
       x = "Percent Urban Tree Coverage", 
       y = "Count") +
  geom_vline(aes(xintercept = mean(UTC_PCT)), color = "blue", alpha = 0.7) +
  geom_vline(aes(xintercept = median(UTC_PCT)), color = "darkorange", alpha = 0.7) +
  geom_text(aes(x=mean(UTC_PCT), label="\nMean", y=10), color="blue", angle=90) +
  geom_text(aes(x=median(UTC_PCT), label="Median\n", y=10), color="darkorange", angle=90)
```


## Linear Regression Models
```{r linear regression models}
#Check correlation between independent variables
correlation_matrix <- cor(school.data[, c("UTC_PCT", "total_trees", "medincomeE.y",
                                          "density", "avg_speed",
                                          "prop_arterial", "total_vol",
                                          "SRTS")], use="complete.obs")
correlation_matrix

#Run linear regression models

#Full model, non log-transformed crashes
full.mdl <- lm(total_crashes~UTC_PCT+total_trees+log.income+density+avg_speed+prop_arterial+total_vol+SRTS, data = school.data)

#Summary and coefficients
summary(full.mdl)
coefficients(full.mdl)

full.mdl.residuals <- residuals(full.mdl) %>%
                      as.data.frame(.)

#Autoplot
full.mdl.plot <- autoplot(full.mdl, which = 1:3, nrow = 3, ncol = 1)

full.mdl.plot

#Distribution of residuals
ggplot(full.mdl.residuals, aes(.)) +
  theme_minimal()+
  labs(title = "Distribution of Residuals") +
  geom_histogram()

#Full model, log-transformed crashes
full.log.mdl <- lm(log_crash~UTC_PCT+total_trees+log.income+density+avg_speed+prop_arterial+total_vol+SRTS, data = school.data)

#Summary and coefficients
summary(full.log.mdl)
coefficients(full.log.mdl)
exp(coefficients(full.log.mdl))

#Autoplot
full.log.mdl.plot <- autoplot(full.log.mdl, which = 1:3, nrow = 3, ncol = 1)

full.log.mdl.plot

#Distribution of residuals
full.log.mdl.residuals <- residuals(full.log.mdl) %>%
  as.data.frame(.)

ggplot(full.log.mdl.residuals, aes(.)) +
  theme_minimal()+
  labs(title = "Distribution of Residuals (log model)") +
  geom_histogram()

#Check VIF
full.log.mdl.vif <- vif(full.log.mdl)

full.log.mdl.vif

#Full model, log-transformed crashes, major or fatal injuries 
full.inj.mdl <- lm(prop_majfat~UTC_PCT+total_trees+log.income+density+avg_speed+prop_arterial+total_vol+SRTS, data = school.data)

#Summary and coefficients
summary(full.inj.mdl)
coefficients(full.inj.mdl)

#Autoplot
full.mdl.inj.plot <- autoplot(full.inj.mdl, which = 1:3, nrow = 3, ncol = 1)

full.mdl.inj.plot

#Distribution of residuals
full.inj.mdl.residuals <- residuals(full.inj.mdl) %>%
  as.data.frame(.)

ggplot(full.inj.mdl.residuals, aes(.)) +
  theme_minimal()+
  labs(title = "Distribution of Residuals") +
  geom_histogram()

#Check VIF
full.inj.mdl.vif <- vif(full.log.inj.mdl)

full.inj.mdl.vif

#Full model, log-transformed crashes, interaction between tree coverage and arterial roads
full.log.mdl.int <- lm(log_crash~UTC_PCT*prop_arterial+total_trees+log.income+density+avg_speed+total_vol+SRTS, data = school.data)

#Summary and coefficients
summary(full.log.mdl.int)
coefficients(full.log.mdl.int)
exp(coefficients(full.log.mdl.int))

#Autoplot
full.log.mdl.int.plot <- autoplot(full.log.mdl.int, which = 1:3, nrow = 3, ncol = 1)

full.log.mdl.int.plot

#Distribution of residuals
full.log.mdl.int.residuals <- residuals(full.log.mdl.int) %>%
  as.data.frame(.)

ggplot(full.log.mdl.int.residuals, aes(.)) +
  theme_minimal()+
  labs(title = "Distribution of Residuals (interaction)") +
  geom_histogram()
```

## Scatter plot
```{r scatter}
ggplot(school.data, aes(x=UTC_PCT, y = log_crash)) +
  geom_point(fill = "darkgrey", size = 3, alpha = 0.5) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Percent Urban Tree Coverage and \nPedestrain Involved Crashes in School Radius (log)", 
       x = "Percent Urban Tree Coverage", 
       y = "Total Number of Crashes (log)") +
  scale_x_continuous(breaks = seq(0,80,10)) +
  scale_y_continuous(breaks = seq(0,5,0.5)) +
  geom_smooth(method = "lm", se = FALSE, alpha = 0.7)

ggplot(school.data, aes(x=UTC_PCT, y = prop_majfat)) +
  geom_point(fill = "darkgrey", size = 3, alpha = 0.5) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(linetype = "solid")
  ) +
  labs(title = "Percent Urban Tree Coverage and \nProportion of Major or Fatal Injuries",
       x = "Percent Urban Tree Coverage", 
       y = "Proportion of Major or Fatal Pedestrian Injuries") +
  scale_x_continuous(breaks = seq(0,80,10)) +
  scale_y_continuous(breaks = seq(0,1,0.1)) +
  geom_smooth(method = "lm", se = FALSE, alpha = 0.7)
```

## Leaflet Map
```{r leaflet}
#Create labels for schools and crashes
school.labels <- paste("<b>", school.data$NAME.x, "</b>", "<br/>", 
                       "Tree Coverage Percent:",school.data$UTC_PCT,"%", "<br/>",
                       "Total Crashes: ",school.data$total_crashes, "<br/>") %>%
  lapply(htmltools::HTML)
 
#Color coding crashes
crash.bins <- c(0,1,2,3,4,5)
crash.color <- colorBin("Purples", bins = crash.bins)

#Color coding coverage
coverage.bins <- c(0,15,30,45,75)
coverage.color <- colorBin("Greens", bins = coverage.bins)

#Color coding median income
income.bins <- c(0,20000,40000,60000,80000, 100000, 150000, 200000, 251000)
income.color <- colorBin("Blues", bins = income.bins)

#Color coding traffic volume
traffic.bins <- c(0,50000,100000,150000,200000,250000,300000,350000, 400000, 650000)
traffic.color <- colorBin("Reds", bins = traffic.bins)

#Color coding proportion arterial
art.bins <- c(0, 0.2, 0.4, 0.6, 0.7, 0.8, 1)
art.color <- colorBin("Oranges", bins = art.bins)

#Create map with school location, radius, and crashes
school.map <- leaflet() %>%
  addProviderTiles(provider = "CartoDB.Positron") %>%
  setView( lng = -77.0369
           , lat = 38.9072
           , zoom = 11) %>%
  addMapPane("points", zIndex = 410) %>%
  #Crashes
  addPolygons(data = school.radius, label = school.labels, stroke = TRUE, fillColor = ~crash.color(school.data$log_crash), color = "#413452", fillOpacity = 0.75,
              highlight = highlightOptions(weight = 5, color = "white",bringToFront = TRUE), group = "Crashes") %>%
  addLegend(pal = crash.color, values = school.data$log_crash, title = "Total Number of Crashes (log)", position = "bottomright", group = "Crashes") %>%
  #Coverage
  addPolygons(data = school.radius, label = school.labels, stroke = TRUE, fillColor = ~coverage.color(school.data$UTC_PCT), color = "darkgreen", fillOpacity = 0.75,
              highlight = highlightOptions(weight = 5, color = "white",bringToFront = TRUE), group = "Tree Coverage") %>%
  addLegend(pal = coverage.color, values = school.data$UTC_PCT, title = "Percent Urban Tree Coverage", position = "bottomright", group = "Tree Coverage") %>%
  #Median Income
  addPolygons(data = school.radius, label = school.labels, stroke = TRUE, fillColor = ~income.color(school.data$medincomeE.y), color = "darkblue", fillOpacity = 0.75,
              highlight = highlightOptions(weight = 5, color = "white",bringToFront = TRUE), group = "Median Income") %>%
  addLegend(pal = income.color, values = school.data$medincomeE.y, title = "Median Income", position = "bottomright", group = "Median Income") %>%
  #Traffic Volume
  addPolygons(data = school.radius, label = school.labels, stroke = TRUE, fillColor = ~traffic.color(school.data$total_vol), color = "darkred", fillOpacity = 0.75,
              highlight = highlightOptions(weight = 5, color = "white",bringToFront = TRUE), group = "Traffic Volume") %>%
  addLegend(pal = traffic.color, values = school.data$total_vol, title = "Average Traffic Volume by Day", position = "bottomright", group = "Traffic Volume") %>%
  #Proportion Arterial
  addPolygons(data = school.radius, label = school.labels, stroke = TRUE, fillColor = ~art.color(school.data$prop_arterial), color = "darkorange", fillOpacity = 0.75,
              highlight = highlightOptions(weight = 5, color = "white",bringToFront = TRUE), group = "Proportion Arterial") %>%
  addLegend(pal = art.color, values = school.data$prop_arterial, title = "Proportion of Arterial Roads", position = "bottomright", group = "Proportion Arterial") %>%
#Crash locations
  addCircleMarkers(data = crash_filter, radius = 1, color = "black", group = "Crash Locations", options = pathOptions(pane = "points")) %>%
#Overlay groups
  addLayersControl(overlayGroups = c("Crashes", "Crash Locations", "Median Income", "Tree Coverage", "Traffic Volume", "Proportion Arterial")) %>%
  hideGroup(c("Crashes", "Tree Coverage", "Median Income", "Traffic Volume", "Proportion Arterial"))

school.map
```
